#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SquadBuilder.Droid.Resource", IsApplication=true)]

namespace SquadBuilder.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::HockeyApp.Resource.Color.hockeyapp_background_header = global::SquadBuilder.Droid.Resource.Color.hockeyapp_background_header;
			global::HockeyApp.Resource.Color.hockeyapp_background_light = global::SquadBuilder.Droid.Resource.Color.hockeyapp_background_light;
			global::HockeyApp.Resource.Color.hockeyapp_background_white = global::SquadBuilder.Droid.Resource.Color.hockeyapp_background_white;
			global::HockeyApp.Resource.Color.hockeyapp_button_background = global::SquadBuilder.Droid.Resource.Color.hockeyapp_button_background;
			global::HockeyApp.Resource.Color.hockeyapp_button_background_pressed = global::SquadBuilder.Droid.Resource.Color.hockeyapp_button_background_pressed;
			global::HockeyApp.Resource.Color.hockeyapp_button_background_selected = global::SquadBuilder.Droid.Resource.Color.hockeyapp_button_background_selected;
			global::HockeyApp.Resource.Color.hockeyapp_text_black = global::SquadBuilder.Droid.Resource.Color.hockeyapp_text_black;
			global::HockeyApp.Resource.Color.hockeyapp_text_light = global::SquadBuilder.Droid.Resource.Color.hockeyapp_text_light;
			global::HockeyApp.Resource.Color.hockeyapp_text_normal = global::SquadBuilder.Droid.Resource.Color.hockeyapp_text_normal;
			global::HockeyApp.Resource.Color.hockeyapp_text_white = global::SquadBuilder.Droid.Resource.Color.hockeyapp_text_white;
			global::HockeyApp.Resource.Drawable.hockeyapp_btn_background = global::SquadBuilder.Droid.Resource.Drawable.hockeyapp_btn_background;
			global::HockeyApp.Resource.Id.button_add_response = global::SquadBuilder.Droid.Resource.Id.button_add_response;
			global::HockeyApp.Resource.Id.button_attachment = global::SquadBuilder.Droid.Resource.Id.button_attachment;
			global::HockeyApp.Resource.Id.button_login = global::SquadBuilder.Droid.Resource.Id.button_login;
			global::HockeyApp.Resource.Id.button_refresh = global::SquadBuilder.Droid.Resource.Id.button_refresh;
			global::HockeyApp.Resource.Id.button_send = global::SquadBuilder.Droid.Resource.Id.button_send;
			global::HockeyApp.Resource.Id.button_update = global::SquadBuilder.Droid.Resource.Id.button_update;
			global::HockeyApp.Resource.Id.input_email = global::SquadBuilder.Droid.Resource.Id.input_email;
			global::HockeyApp.Resource.Id.input_message = global::SquadBuilder.Droid.Resource.Id.input_message;
			global::HockeyApp.Resource.Id.input_name = global::SquadBuilder.Droid.Resource.Id.input_name;
			global::HockeyApp.Resource.Id.input_password = global::SquadBuilder.Droid.Resource.Id.input_password;
			global::HockeyApp.Resource.Id.input_subject = global::SquadBuilder.Droid.Resource.Id.input_subject;
			global::HockeyApp.Resource.Id.label_author = global::SquadBuilder.Droid.Resource.Id.label_author;
			global::HockeyApp.Resource.Id.label_date = global::SquadBuilder.Droid.Resource.Id.label_date;
			global::HockeyApp.Resource.Id.label_last_updated = global::SquadBuilder.Droid.Resource.Id.label_last_updated;
			global::HockeyApp.Resource.Id.label_message = global::SquadBuilder.Droid.Resource.Id.label_message;
			global::HockeyApp.Resource.Id.label_text = global::SquadBuilder.Droid.Resource.Id.label_text;
			global::HockeyApp.Resource.Id.label_title = global::SquadBuilder.Droid.Resource.Id.label_title;
			global::HockeyApp.Resource.Id.label_version = global::SquadBuilder.Droid.Resource.Id.label_version;
			global::HockeyApp.Resource.Id.list_attachments = global::SquadBuilder.Droid.Resource.Id.list_attachments;
			global::HockeyApp.Resource.Id.list_feedback_messages = global::SquadBuilder.Droid.Resource.Id.list_feedback_messages;
			global::HockeyApp.Resource.Id.text_headline = global::SquadBuilder.Droid.Resource.Id.text_headline;
			global::HockeyApp.Resource.Id.view_header = global::SquadBuilder.Droid.Resource.Id.view_header;
			global::HockeyApp.Resource.Id.web_update_details = global::SquadBuilder.Droid.Resource.Id.web_update_details;
			global::HockeyApp.Resource.Id.wrapper_attachments = global::SquadBuilder.Droid.Resource.Id.wrapper_attachments;
			global::HockeyApp.Resource.Id.wrapper_feedback = global::SquadBuilder.Droid.Resource.Id.wrapper_feedback;
			global::HockeyApp.Resource.Id.wrapper_feedback_scroll = global::SquadBuilder.Droid.Resource.Id.wrapper_feedback_scroll;
			global::HockeyApp.Resource.Id.wrapper_messages = global::SquadBuilder.Droid.Resource.Id.wrapper_messages;
			global::HockeyApp.Resource.Id.wrapper_messages_buttons = global::SquadBuilder.Droid.Resource.Id.wrapper_messages_buttons;
			global::HockeyApp.Resource.Layout.hockeyapp_activity_expiry_info = global::SquadBuilder.Droid.Resource.Layout.hockeyapp_activity_expiry_info;
			global::HockeyApp.Resource.Layout.hockeyapp_activity_feedback = global::SquadBuilder.Droid.Resource.Layout.hockeyapp_activity_feedback;
			global::HockeyApp.Resource.Layout.hockeyapp_activity_login = global::SquadBuilder.Droid.Resource.Layout.hockeyapp_activity_login;
			global::HockeyApp.Resource.Layout.hockeyapp_activity_update = global::SquadBuilder.Droid.Resource.Layout.hockeyapp_activity_update;
			global::HockeyApp.Resource.Layout.hockeyapp_fragment_update = global::SquadBuilder.Droid.Resource.Layout.hockeyapp_fragment_update;
			global::HockeyApp.Resource.Layout.hockeyapp_view_feedback_message = global::SquadBuilder.Droid.Resource.Layout.hockeyapp_view_feedback_message;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_app_name_fallback = global::SquadBuilder.Droid.Resource.String.hockeyapp_crash_dialog_app_name_fallback;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_message = global::SquadBuilder.Droid.Resource.String.hockeyapp_crash_dialog_message;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_negative_button = global::SquadBuilder.Droid.Resource.String.hockeyapp_crash_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_neutral_button = global::SquadBuilder.Droid.Resource.String.hockeyapp_crash_dialog_neutral_button;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_positive_button = global::SquadBuilder.Droid.Resource.String.hockeyapp_crash_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_title = global::SquadBuilder.Droid.Resource.String.hockeyapp_crash_dialog_title;
			global::HockeyApp.Resource.String.hockeyapp_dialog_error_message = global::SquadBuilder.Droid.Resource.String.hockeyapp_dialog_error_message;
			global::HockeyApp.Resource.String.hockeyapp_dialog_error_title = global::SquadBuilder.Droid.Resource.String.hockeyapp_dialog_error_title;
			global::HockeyApp.Resource.String.hockeyapp_dialog_negative_button = global::SquadBuilder.Droid.Resource.String.hockeyapp_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_dialog_positive_button = global::SquadBuilder.Droid.Resource.String.hockeyapp_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_download_failed_dialog_message = global::SquadBuilder.Droid.Resource.String.hockeyapp_download_failed_dialog_message;
			global::HockeyApp.Resource.String.hockeyapp_download_failed_dialog_negative_button = global::SquadBuilder.Droid.Resource.String.hockeyapp_download_failed_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_download_failed_dialog_positive_button = global::SquadBuilder.Droid.Resource.String.hockeyapp_download_failed_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_download_failed_dialog_title = global::SquadBuilder.Droid.Resource.String.hockeyapp_download_failed_dialog_title;
			global::HockeyApp.Resource.String.hockeyapp_error_no_network_message = global::SquadBuilder.Droid.Resource.String.hockeyapp_error_no_network_message;
			global::HockeyApp.Resource.String.hockeyapp_expiry_info_text = global::SquadBuilder.Droid.Resource.String.hockeyapp_expiry_info_text;
			global::HockeyApp.Resource.String.hockeyapp_expiry_info_title = global::SquadBuilder.Droid.Resource.String.hockeyapp_expiry_info_title;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attach_file = global::SquadBuilder.Droid.Resource.String.hockeyapp_feedback_attach_file;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attach_picture = global::SquadBuilder.Droid.Resource.String.hockeyapp_feedback_attach_picture;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attachment_button_text = global::SquadBuilder.Droid.Resource.String.hockeyapp_feedback_attachment_button_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attachment_error = global::SquadBuilder.Droid.Resource.String.hockeyapp_feedback_attachment_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attachment_loading = global::SquadBuilder.Droid.Resource.String.hockeyapp_feedback_attachment_loading;
			global::HockeyApp.Resource.String.hockeyapp_feedback_email_hint = global::SquadBuilder.Droid.Resource.String.hockeyapp_feedback_email_hint;
			global::HockeyApp.Resource.String.hockeyapp_feedback_failed_text = global::SquadBuilder.Droid.Resource.String.hockeyapp_feedback_failed_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_failed_title = global::SquadBuilder.Droid.Resource.String.hockeyapp_feedback_failed_title;
			global::HockeyApp.Resource.String.hockeyapp_feedback_fetching_feedback_text = global::SquadBuilder.Droid.Resource.String.hockeyapp_feedback_fetching_feedback_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_generic_error = global::SquadBuilder.Droid.Resource.String.hockeyapp_feedback_generic_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_last_updated_text = global::SquadBuilder.Droid.Resource.String.hockeyapp_feedback_last_updated_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_max_attachments_allowed = global::SquadBuilder.Droid.Resource.String.hockeyapp_feedback_max_attachments_allowed;
			global::HockeyApp.Resource.String.hockeyapp_feedback_message_hint = global::SquadBuilder.Droid.Resource.String.hockeyapp_feedback_message_hint;
			global::HockeyApp.Resource.String.hockeyapp_feedback_name_hint = global::SquadBuilder.Droid.Resource.String.hockeyapp_feedback_name_hint;
			global::HockeyApp.Resource.String.hockeyapp_feedback_refresh_button_text = global::SquadBuilder.Droid.Resource.String.hockeyapp_feedback_refresh_button_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_response_button_text = global::SquadBuilder.Droid.Resource.String.hockeyapp_feedback_response_button_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_select_file = global::SquadBuilder.Droid.Resource.String.hockeyapp_feedback_select_file;
			global::HockeyApp.Resource.String.hockeyapp_feedback_select_picture = global::SquadBuilder.Droid.Resource.String.hockeyapp_feedback_select_picture;
			global::HockeyApp.Resource.String.hockeyapp_feedback_send_button_text = global::SquadBuilder.Droid.Resource.String.hockeyapp_feedback_send_button_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_send_generic_error = global::SquadBuilder.Droid.Resource.String.hockeyapp_feedback_send_generic_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_send_network_error = global::SquadBuilder.Droid.Resource.String.hockeyapp_feedback_send_network_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_sending_feedback_text = global::SquadBuilder.Droid.Resource.String.hockeyapp_feedback_sending_feedback_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_subject_hint = global::SquadBuilder.Droid.Resource.String.hockeyapp_feedback_subject_hint;
			global::HockeyApp.Resource.String.hockeyapp_feedback_title = global::SquadBuilder.Droid.Resource.String.hockeyapp_feedback_title;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_email_empty = global::SquadBuilder.Droid.Resource.String.hockeyapp_feedback_validate_email_empty;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_email_error = global::SquadBuilder.Droid.Resource.String.hockeyapp_feedback_validate_email_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_name_error = global::SquadBuilder.Droid.Resource.String.hockeyapp_feedback_validate_name_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_subject_error = global::SquadBuilder.Droid.Resource.String.hockeyapp_feedback_validate_subject_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_text_error = global::SquadBuilder.Droid.Resource.String.hockeyapp_feedback_validate_text_error;
			global::HockeyApp.Resource.String.hockeyapp_login_email_hint = global::SquadBuilder.Droid.Resource.String.hockeyapp_login_email_hint;
			global::HockeyApp.Resource.String.hockeyapp_login_headline_text = global::SquadBuilder.Droid.Resource.String.hockeyapp_login_headline_text;
			global::HockeyApp.Resource.String.hockeyapp_login_headline_text_email_only = global::SquadBuilder.Droid.Resource.String.hockeyapp_login_headline_text_email_only;
			global::HockeyApp.Resource.String.hockeyapp_login_login_button_text = global::SquadBuilder.Droid.Resource.String.hockeyapp_login_login_button_text;
			global::HockeyApp.Resource.String.hockeyapp_login_missing_credentials_toast = global::SquadBuilder.Droid.Resource.String.hockeyapp_login_missing_credentials_toast;
			global::HockeyApp.Resource.String.hockeyapp_login_password_hint = global::SquadBuilder.Droid.Resource.String.hockeyapp_login_password_hint;
			global::HockeyApp.Resource.String.hockeyapp_paint_dialog_message = global::SquadBuilder.Droid.Resource.String.hockeyapp_paint_dialog_message;
			global::HockeyApp.Resource.String.hockeyapp_paint_dialog_negative_button = global::SquadBuilder.Droid.Resource.String.hockeyapp_paint_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_paint_dialog_neutral_button = global::SquadBuilder.Droid.Resource.String.hockeyapp_paint_dialog_neutral_button;
			global::HockeyApp.Resource.String.hockeyapp_paint_dialog_positive_button = global::SquadBuilder.Droid.Resource.String.hockeyapp_paint_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_paint_indicator_toast = global::SquadBuilder.Droid.Resource.String.hockeyapp_paint_indicator_toast;
			global::HockeyApp.Resource.String.hockeyapp_paint_menu_clear = global::SquadBuilder.Droid.Resource.String.hockeyapp_paint_menu_clear;
			global::HockeyApp.Resource.String.hockeyapp_paint_menu_save = global::SquadBuilder.Droid.Resource.String.hockeyapp_paint_menu_save;
			global::HockeyApp.Resource.String.hockeyapp_paint_menu_undo = global::SquadBuilder.Droid.Resource.String.hockeyapp_paint_menu_undo;
			global::HockeyApp.Resource.String.hockeyapp_permission_dialog_negative_button = global::SquadBuilder.Droid.Resource.String.hockeyapp_permission_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_permission_dialog_positive_button = global::SquadBuilder.Droid.Resource.String.hockeyapp_permission_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_permission_update_message = global::SquadBuilder.Droid.Resource.String.hockeyapp_permission_update_message;
			global::HockeyApp.Resource.String.hockeyapp_permission_update_title = global::SquadBuilder.Droid.Resource.String.hockeyapp_permission_update_title;
			global::HockeyApp.Resource.String.hockeyapp_update_button = global::SquadBuilder.Droid.Resource.String.hockeyapp_update_button;
			global::HockeyApp.Resource.String.hockeyapp_update_dialog_message = global::SquadBuilder.Droid.Resource.String.hockeyapp_update_dialog_message;
			global::HockeyApp.Resource.String.hockeyapp_update_dialog_negative_button = global::SquadBuilder.Droid.Resource.String.hockeyapp_update_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_update_dialog_positive_button = global::SquadBuilder.Droid.Resource.String.hockeyapp_update_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_update_dialog_title = global::SquadBuilder.Droid.Resource.String.hockeyapp_update_dialog_title;
			global::HockeyApp.Resource.String.hockeyapp_update_mandatory_toast = global::SquadBuilder.Droid.Resource.String.hockeyapp_update_mandatory_toast;
			global::HockeyApp.Resource.String.hockeyapp_update_version_details_label = global::SquadBuilder.Droid.Resource.String.hockeyapp_update_version_details_label;
			global::HockeyApp.Resource.String.library_name = global::SquadBuilder.Droid.Resource.String.library_name;
			global::HockeyApp.Resource.Style.HockeyApp_ButtonStyle = global::SquadBuilder.Droid.Resource.Style.HockeyApp_ButtonStyle;
			global::HockeyApp.Resource.Style.HockeyApp_EditTextStyle = global::SquadBuilder.Droid.Resource.Style.HockeyApp_EditTextStyle;
			global::HockeyApp.Resource.Style.HockeyApp_SingleLineInputStyle = global::SquadBuilder.Droid.Resource.Style.HockeyApp_SingleLineInputStyle;
			global::PerpetualMobile.Storage.Resource.String.library_name = global::SquadBuilder.Droid.Resource.String.library_name;
			global::XLabs.Forms.Resource.Color.calendar_active_month_bg = global::SquadBuilder.Droid.Resource.Color.calendar_active_month_bg;
			global::XLabs.Forms.Resource.Color.calendar_bg = global::SquadBuilder.Droid.Resource.Color.calendar_bg;
			global::XLabs.Forms.Resource.Color.calendar_divider = global::SquadBuilder.Droid.Resource.Color.calendar_divider;
			global::XLabs.Forms.Resource.Color.calendar_highlighted_day_bg = global::SquadBuilder.Droid.Resource.Color.calendar_highlighted_day_bg;
			global::XLabs.Forms.Resource.Color.calendar_inactive_month_bg = global::SquadBuilder.Droid.Resource.Color.calendar_inactive_month_bg;
			global::XLabs.Forms.Resource.Color.calendar_selected_day_bg = global::SquadBuilder.Droid.Resource.Color.calendar_selected_day_bg;
			global::XLabs.Forms.Resource.Color.calendar_selected_range_bg = global::SquadBuilder.Droid.Resource.Color.calendar_selected_range_bg;
			global::XLabs.Forms.Resource.Color.calendar_text_active = global::SquadBuilder.Droid.Resource.Color.calendar_text_active;
			global::XLabs.Forms.Resource.Color.calendar_text_inactive = global::SquadBuilder.Droid.Resource.Color.calendar_text_inactive;
			global::XLabs.Forms.Resource.Color.calendar_text_selected = global::SquadBuilder.Droid.Resource.Color.calendar_text_selected;
			global::XLabs.Forms.Resource.Color.calendar_text_selector = global::SquadBuilder.Droid.Resource.Color.calendar_text_selector;
			global::XLabs.Forms.Resource.Color.calendar_text_unselectable = global::SquadBuilder.Droid.Resource.Color.calendar_text_unselectable;
			global::XLabs.Forms.Resource.Dimension.calendar_day_headers_paddingbottom = global::SquadBuilder.Droid.Resource.Dimension.calendar_day_headers_paddingbottom;
			global::XLabs.Forms.Resource.Dimension.calendar_month_title_bottommargin = global::SquadBuilder.Droid.Resource.Dimension.calendar_month_title_bottommargin;
			global::XLabs.Forms.Resource.Dimension.calendar_month_topmargin = global::SquadBuilder.Droid.Resource.Dimension.calendar_month_topmargin;
			global::XLabs.Forms.Resource.Dimension.calendar_text_medium = global::SquadBuilder.Droid.Resource.Dimension.calendar_text_medium;
			global::XLabs.Forms.Resource.Dimension.calendar_text_small = global::SquadBuilder.Droid.Resource.Dimension.calendar_text_small;
			global::XLabs.Forms.Resource.Drawable.ad16 = global::SquadBuilder.Droid.Resource.Drawable.ad16;
			global::XLabs.Forms.Resource.Drawable.calendar_bg_selector = global::SquadBuilder.Droid.Resource.Drawable.calendar_bg_selector;
			global::XLabs.Forms.Resource.Id.calendar_grid = global::SquadBuilder.Droid.Resource.Id.calendar_grid;
			global::XLabs.Forms.Resource.Id.calendar_view = global::SquadBuilder.Droid.Resource.Id.calendar_view;
			global::XLabs.Forms.Resource.Id.left_arrow = global::SquadBuilder.Droid.Resource.Id.left_arrow;
			global::XLabs.Forms.Resource.Id.right_arrow = global::SquadBuilder.Droid.Resource.Id.right_arrow;
			global::XLabs.Forms.Resource.Id.title = global::SquadBuilder.Droid.Resource.Id.title;
			global::XLabs.Forms.Resource.Layout.calendar_pager_layout = global::SquadBuilder.Droid.Resource.Layout.calendar_pager_layout;
			global::XLabs.Forms.Resource.Layout.calendar_picker = global::SquadBuilder.Droid.Resource.Layout.calendar_picker;
			global::XLabs.Forms.Resource.Layout.dialog = global::SquadBuilder.Droid.Resource.Layout.dialog;
			global::XLabs.Forms.Resource.Layout.month = global::SquadBuilder.Droid.Resource.Layout.month;
			global::XLabs.Forms.Resource.Layout.week = global::SquadBuilder.Droid.Resource.Layout.week;
			global::XLabs.Forms.Resource.String.ApplicationName = global::SquadBuilder.Droid.Resource.String.ApplicationName;
			global::XLabs.Forms.Resource.String.Hello = global::SquadBuilder.Droid.Resource.String.Hello;
			global::XLabs.Forms.Resource.String.day_name_format = global::SquadBuilder.Droid.Resource.String.day_name_format;
			global::XLabs.Forms.Resource.String.full_date_format = global::SquadBuilder.Droid.Resource.String.full_date_format;
			global::XLabs.Forms.Resource.String.invalid_date = global::SquadBuilder.Droid.Resource.String.invalid_date;
			global::XLabs.Forms.Resource.String.library_name = global::SquadBuilder.Droid.Resource.String.library_name;
			global::XLabs.Forms.Resource.String.month_name_format = global::SquadBuilder.Droid.Resource.String.month_name_format;
			global::XLabs.Forms.Resource.Style.CalendarCell = global::SquadBuilder.Droid.Resource.Style.CalendarCell;
			global::XLabs.Forms.Resource.Style.CalendarCell_CalendarDate = global::SquadBuilder.Droid.Resource.Style.CalendarCell_CalendarDate;
			global::XLabs.Forms.Resource.Style.CalendarCell_DayHeader = global::SquadBuilder.Droid.Resource.Style.CalendarCell_DayHeader;
			global::XLabs.Forms.Resource.Style.CalendarTitle = global::SquadBuilder.Droid.Resource.Style.CalendarTitle;
			global::XLabs.Platform.Resource.String.ApplicationName = global::SquadBuilder.Droid.Resource.String.ApplicationName;
			global::XLabs.Platform.Resource.String.Hello = global::SquadBuilder.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int calendar_active_month_bg = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int calendar_bg = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int calendar_divider = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int calendar_highlighted_day_bg = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int calendar_inactive_month_bg = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int calendar_selected_day_bg = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int calendar_selected_range_bg = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int calendar_text_active = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int calendar_text_inactive = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int calendar_text_selected = 2131034121;
			
			// aapt resource value: 0x7f050015
			public const int calendar_text_selector = 2131034133;
			
			// aapt resource value: 0x7f05000a
			public const int calendar_text_unselectable = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int hockeyapp_background_header = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int hockeyapp_background_light = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int hockeyapp_background_white = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int hockeyapp_button_background = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int hockeyapp_button_background_pressed = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int hockeyapp_button_background_selected = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int hockeyapp_text_black = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int hockeyapp_text_light = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int hockeyapp_text_normal = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int hockeyapp_text_white = 2131034132;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f060000
			public const int calendar_day_headers_paddingbottom = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int calendar_month_title_bottommargin = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int calendar_month_topmargin = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int calendar_text_medium = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int calendar_text_small = 2131099652;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ad16 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int AggressorDial = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Arc170Dial = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Arc170DialNienNumb = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Arc170Dialr2astro = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int AssaultGunboatDial = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int AttackShuttleDial = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int AttackShuttleDialNienNumb = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int AwingDial = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int BwingDial = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int BwingDialNienNumb = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int calendar_bg_selector = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int EwingDial = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int EwingDialr2astro = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int FiresprayDial = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int G1ADial = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int hamburger = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int hockeyapp_btn_background = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int HWK290Dial = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int HWK290DialNienNumb = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int icon = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int JumpMasterDial = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int JumpMasterDialUnhinged = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int KihraxzDial = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int KwingDial = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int KwingDialNienNumb = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int LambdaDial = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int LancerDial = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ProtectorateDial = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int QuadjumperDial = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ScykDial = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int SoroSuubDial = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int StarViperDial = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int T70XwingDial = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int T70XwingDialr2astro = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int TIEAdvancedDial = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int TIEAdvancedDialMk2 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int TIEAdvPrototypeDial = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int TIEAdvPrototypeDialMk2 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int TIEAvengerDial = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int TIEAvengerDialMk2 = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int TIEBomberDial = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int TIEBomberDialMk2 = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int TIEDefenderDial = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int TIEDefenderDialMk2 = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int TIEFighterDial = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int TIEFighterDialMk2 = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int TIEFODial = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int TIEFODialMk2 = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int TIEInterceptorDial = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int TIEInterceptorDialMk2 = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int TIEPhantomDial = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int TIEPhantomDialMk2 = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int TIEPunisherDial = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int TIEPunisherDialMk2 = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int TIESFDial = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int TIESFDialMk2 = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int TIEStrikerDial = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int TIEStrikerDialMk2 = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int UpsilonDial = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int UWingDial = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int UWingDialNienNumb = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int VCX100Dial = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int VCX100DialNienNumb = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int VT49Dial = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int VwingDial = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int XwingDial = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int XwingDialr2astro = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int YT1300Dial = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int YT1300DialNienNumb = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int YT2400Dial = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int YT2400DialNienNumb = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int YV666Dial = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int YwingDial = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int YwingDialr2astro = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int YwingDialUnhinged = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int Z95Dial = 2130837580;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080011
			public const int button_add_response = 2131230737;
			
			// aapt resource value: 0x7f08000c
			public const int button_attachment = 2131230732;
			
			// aapt resource value: 0x7f080016
			public const int button_login = 2131230742;
			
			// aapt resource value: 0x7f080012
			public const int button_refresh = 2131230738;
			
			// aapt resource value: 0x7f08000d
			public const int button_send = 2131230733;
			
			// aapt resource value: 0x7f08001a
			public const int button_update = 2131230746;
			
			// aapt resource value: 0x7f080020
			public const int calendar_grid = 2131230752;
			
			// aapt resource value: 0x7f080001
			public const int calendar_view = 2131230721;
			
			// aapt resource value: 0x7f080008
			public const int input_email = 2131230728;
			
			// aapt resource value: 0x7f08000a
			public const int input_message = 2131230730;
			
			// aapt resource value: 0x7f080007
			public const int input_name = 2131230727;
			
			// aapt resource value: 0x7f080015
			public const int input_password = 2131230741;
			
			// aapt resource value: 0x7f080009
			public const int input_subject = 2131230729;
			
			// aapt resource value: 0x7f08001c
			public const int label_author = 2131230748;
			
			// aapt resource value: 0x7f08001d
			public const int label_date = 2131230749;
			
			// aapt resource value: 0x7f08000f
			public const int label_last_updated = 2131230735;
			
			// aapt resource value: 0x7f080004
			public const int label_message = 2131230724;
			
			// aapt resource value: 0x7f08001e
			public const int label_text = 2131230750;
			
			// aapt resource value: 0x7f080018
			public const int label_title = 2131230744;
			
			// aapt resource value: 0x7f080019
			public const int label_version = 2131230745;
			
			// aapt resource value: 0x7f080003
			public const int left_arrow = 2131230723;
			
			// aapt resource value: 0x7f08001f
			public const int list_attachments = 2131230751;
			
			// aapt resource value: 0x7f080013
			public const int list_feedback_messages = 2131230739;
			
			// aapt resource value: 0x7f080002
			public const int right_arrow = 2131230722;
			
			// aapt resource value: 0x7f080014
			public const int text_headline = 2131230740;
			
			// aapt resource value: 0x7f080000
			public const int title = 2131230720;
			
			// aapt resource value: 0x7f080017
			public const int view_header = 2131230743;
			
			// aapt resource value: 0x7f08001b
			public const int web_update_details = 2131230747;
			
			// aapt resource value: 0x7f08000b
			public const int wrapper_attachments = 2131230731;
			
			// aapt resource value: 0x7f080006
			public const int wrapper_feedback = 2131230726;
			
			// aapt resource value: 0x7f080005
			public const int wrapper_feedback_scroll = 2131230725;
			
			// aapt resource value: 0x7f08000e
			public const int wrapper_messages = 2131230734;
			
			// aapt resource value: 0x7f080010
			public const int wrapper_messages_buttons = 2131230736;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int calendar_pager_layout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int calendar_picker = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int dialog = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int hockeyapp_activity_expiry_info = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int hockeyapp_activity_feedback = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int hockeyapp_activity_login = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int hockeyapp_activity_update = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int hockeyapp_fragment_update = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int hockeyapp_view_feedback_message = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int month = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int week = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int day_name_format = 2130968579;
			
			// aapt resource value: 0x7f040006
			public const int full_date_format = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int hockeyapp_crash_dialog_app_name_fallback = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int hockeyapp_crash_dialog_message = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int hockeyapp_crash_dialog_negative_button = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int hockeyapp_crash_dialog_neutral_button = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int hockeyapp_crash_dialog_positive_button = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int hockeyapp_crash_dialog_title = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int hockeyapp_dialog_error_message = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int hockeyapp_dialog_error_title = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int hockeyapp_dialog_negative_button = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int hockeyapp_dialog_positive_button = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int hockeyapp_download_failed_dialog_message = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int hockeyapp_download_failed_dialog_negative_button = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int hockeyapp_download_failed_dialog_positive_button = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int hockeyapp_download_failed_dialog_title = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int hockeyapp_error_no_network_message = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int hockeyapp_expiry_info_text = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int hockeyapp_expiry_info_title = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int hockeyapp_feedback_attach_file = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int hockeyapp_feedback_attach_picture = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public const int hockeyapp_feedback_attachment_button_text = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public const int hockeyapp_feedback_attachment_error = 2130968603;
			
			// aapt resource value: 0x7f04001c
			public const int hockeyapp_feedback_attachment_loading = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int hockeyapp_feedback_email_hint = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int hockeyapp_feedback_failed_text = 2130968606;
			
			// aapt resource value: 0x7f04001f
			public const int hockeyapp_feedback_failed_title = 2130968607;
			
			// aapt resource value: 0x7f040020
			public const int hockeyapp_feedback_fetching_feedback_text = 2130968608;
			
			// aapt resource value: 0x7f040021
			public const int hockeyapp_feedback_generic_error = 2130968609;
			
			// aapt resource value: 0x7f040022
			public const int hockeyapp_feedback_last_updated_text = 2130968610;
			
			// aapt resource value: 0x7f040023
			public const int hockeyapp_feedback_max_attachments_allowed = 2130968611;
			
			// aapt resource value: 0x7f040024
			public const int hockeyapp_feedback_message_hint = 2130968612;
			
			// aapt resource value: 0x7f040025
			public const int hockeyapp_feedback_name_hint = 2130968613;
			
			// aapt resource value: 0x7f040026
			public const int hockeyapp_feedback_refresh_button_text = 2130968614;
			
			// aapt resource value: 0x7f040027
			public const int hockeyapp_feedback_response_button_text = 2130968615;
			
			// aapt resource value: 0x7f040028
			public const int hockeyapp_feedback_select_file = 2130968616;
			
			// aapt resource value: 0x7f040029
			public const int hockeyapp_feedback_select_picture = 2130968617;
			
			// aapt resource value: 0x7f04002a
			public const int hockeyapp_feedback_send_button_text = 2130968618;
			
			// aapt resource value: 0x7f04002b
			public const int hockeyapp_feedback_send_generic_error = 2130968619;
			
			// aapt resource value: 0x7f04002c
			public const int hockeyapp_feedback_send_network_error = 2130968620;
			
			// aapt resource value: 0x7f04002d
			public const int hockeyapp_feedback_sending_feedback_text = 2130968621;
			
			// aapt resource value: 0x7f04002e
			public const int hockeyapp_feedback_subject_hint = 2130968622;
			
			// aapt resource value: 0x7f04002f
			public const int hockeyapp_feedback_title = 2130968623;
			
			// aapt resource value: 0x7f040030
			public const int hockeyapp_feedback_validate_email_empty = 2130968624;
			
			// aapt resource value: 0x7f040031
			public const int hockeyapp_feedback_validate_email_error = 2130968625;
			
			// aapt resource value: 0x7f040032
			public const int hockeyapp_feedback_validate_name_error = 2130968626;
			
			// aapt resource value: 0x7f040033
			public const int hockeyapp_feedback_validate_subject_error = 2130968627;
			
			// aapt resource value: 0x7f040034
			public const int hockeyapp_feedback_validate_text_error = 2130968628;
			
			// aapt resource value: 0x7f040035
			public const int hockeyapp_login_email_hint = 2130968629;
			
			// aapt resource value: 0x7f040036
			public const int hockeyapp_login_headline_text = 2130968630;
			
			// aapt resource value: 0x7f040037
			public const int hockeyapp_login_headline_text_email_only = 2130968631;
			
			// aapt resource value: 0x7f040038
			public const int hockeyapp_login_login_button_text = 2130968632;
			
			// aapt resource value: 0x7f040039
			public const int hockeyapp_login_missing_credentials_toast = 2130968633;
			
			// aapt resource value: 0x7f04003a
			public const int hockeyapp_login_password_hint = 2130968634;
			
			// aapt resource value: 0x7f04003b
			public const int hockeyapp_paint_dialog_message = 2130968635;
			
			// aapt resource value: 0x7f04003c
			public const int hockeyapp_paint_dialog_negative_button = 2130968636;
			
			// aapt resource value: 0x7f04003d
			public const int hockeyapp_paint_dialog_neutral_button = 2130968637;
			
			// aapt resource value: 0x7f04003e
			public const int hockeyapp_paint_dialog_positive_button = 2130968638;
			
			// aapt resource value: 0x7f04003f
			public const int hockeyapp_paint_indicator_toast = 2130968639;
			
			// aapt resource value: 0x7f040040
			public const int hockeyapp_paint_menu_clear = 2130968640;
			
			// aapt resource value: 0x7f040041
			public const int hockeyapp_paint_menu_save = 2130968641;
			
			// aapt resource value: 0x7f040042
			public const int hockeyapp_paint_menu_undo = 2130968642;
			
			// aapt resource value: 0x7f040043
			public const int hockeyapp_permission_dialog_negative_button = 2130968643;
			
			// aapt resource value: 0x7f040044
			public const int hockeyapp_permission_dialog_positive_button = 2130968644;
			
			// aapt resource value: 0x7f040045
			public const int hockeyapp_permission_update_message = 2130968645;
			
			// aapt resource value: 0x7f040046
			public const int hockeyapp_permission_update_title = 2130968646;
			
			// aapt resource value: 0x7f040047
			public const int hockeyapp_update_button = 2130968647;
			
			// aapt resource value: 0x7f040048
			public const int hockeyapp_update_dialog_message = 2130968648;
			
			// aapt resource value: 0x7f040049
			public const int hockeyapp_update_dialog_negative_button = 2130968649;
			
			// aapt resource value: 0x7f04004a
			public const int hockeyapp_update_dialog_positive_button = 2130968650;
			
			// aapt resource value: 0x7f04004b
			public const int hockeyapp_update_dialog_title = 2130968651;
			
			// aapt resource value: 0x7f04004c
			public const int hockeyapp_update_mandatory_toast = 2130968652;
			
			// aapt resource value: 0x7f04004d
			public const int hockeyapp_update_version_details_label = 2130968653;
			
			// aapt resource value: 0x7f040004
			public const int invalid_date = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int library_name = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int month_name_format = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int CalendarCell = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int CalendarCell_CalendarDate = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int CalendarCell_DayHeader = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int CalendarTitle = 2131165184;
			
			// aapt resource value: 0x7f070007
			public const int CustomTheme = 2131165191;
			
			// aapt resource value: 0x7f070004
			public const int HockeyApp_ButtonStyle = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int HockeyApp_EditTextStyle = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int HockeyApp_SingleLineInputStyle = 2131165190;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
